### ISSUE TITLE
Disble mark as read

### ISSUE THREAD

**Issue by antonshiryaev** [tbunnyman/ReadItLater-Calibre-Plugin#30]
How can I disable Mark as Read for downloaded articles? That feature is really useless, and I don't want all my articles disappearing after download.

**Comment by Wiltons** [comment]
Hi,

You can set change the mark_as_read_after_dl setting.
It should read mark_as_read_after_dl = False

~Cillian

**Comment by tbunnyman** [comment]
This is correct. It is a setting in the script. Please red the top notes for more things you can change as well

**Comment by antonshiryaev** [comment]
Problem solved. Thanks a lot.
