### ISSUE TITLE
can't download any article

### ISSUE THREAD

**Issue by radlerandi** [tbunnyman/ReadItLater-Calibre-Plugin#34]
the plugin worked already, but after a few months i just wanted to download new articles and none of them is downloaded.
the log says to every article something like this:

Failed to download article: Helden ohne Plan from http://getpocket.com/a/read/981144633
Traceback (most recent call last):
  File "site-packages/calibre/utils/threadpool.py", line 95, in run
  File "site-packages/calibre/web/feeds/news.py", line 1156, in fetch_obfuscated_article
  File "<string>", line 157, in get_obfuscated_article
  File "<string>", line 150, in get_textview
KeyError: 'article'

**Comment by tbunnyman** [comment]
Sounds like Pocket may have updated their page loads and the code here can't find any of the articles any more. This plugin works by scraping the page and not any api. I am not currently maintaining this project anymore but I invite any PRs to hopefully fix the issues.

**Comment by radlerandi** [comment]
i had a modified pocket recipe, and i've just created a new modified version from the integrated one: article download works again :)
